var level_null = [
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
palitra_color.white,
];

var maslevel=[
    //тренеровка 1
            [
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "    xxxxxxxxxxxxxxxxxxxx   ",
            "    x                  x   ",
            "    x @              * x   ",
            "    x                  x   ",
            "    xxxxxxxxxxxxxxxxxxxx   ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
        palitra_color.white,
],
    //тренеровка 2
            [
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "    xxxxxxxxxxxxxxxxxxx    ",
                "    x          r      x    ",
                "    x  R   @   r   *  x    ",
                "    x          r      x    ",
                "    xxxxxxxxxxxxxxxxxxx    ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
            palitra_color.white,
],
    //тренеровка 3
            [
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "       xxxxxxxxxxxxxxxxx   ",
                "       x         g     x   ",
                "       x  *      g  G  x   ",
                "       x         g     x   ",
                "       xxxxxxxxxxxxbbbxx   ",
                "       x         r     x   ",
                "       x  @   R  r  B  x   ",
                "       x         r     x   ",
                "       xxxxxxxxxxxxxxxxx   ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                palitra_color.white,
            ],
    //уровень 1
    [
"Gg                       gR",
"b                         r",
"                           ",
"                           ",
"                           ",
"                           ",
"                           ",
"                           ",
"                           ",
"                           ",
"             @             ",
"                           ",
"                           ",
"                      rr   ",
"                     r  r  ",
"                    r G r  ",
"                    r   gxx",
"                     rrg   ",
"b                      x * ",
"B                      x   ",
palitra_color.white,
],
    
    //
    [
	"@                          ",
	"                           ",
	"                           ",
	"                           ",
	"                           ",
	"                           ",
	"                           ",
	"                           ",
	"                           ",	
	"                 ggg bbb   ",
	"                g   b   b  ",
	"              G g B b R b  ",
	"                g   b   b  ",
	"                 ggg rrr   ",	
	"                    r   r  ",
	"                    r G r  ",
	"                    r   gxx",
	"                     rrg   ",
	"                       x * ",
	"                       x   ",
	palitra_color.white,
],
    //уровень 1
            [
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                " xxxxxxxxxxxxxxxxxxxxxx    ",
                " x   x        x       x    ",
                " x * x        B       xxxxx",
                " x   x        x           x",
                " xbbbx        x           x",
                " x @ x        x           x",
                " x   xxxxxbbbxxxxxggxxxbbbx",
                " x   r                    x",
                " x   r                    x",
                " x   xxxxxxxxxxxxxxxxxx   x",
                " x      b          b      x",
                " x    R xxxxxxxxxxxxG     x",
                " x      x          xxxxxxxx",
                " xxxxxxxx                  ",
                "                           ",
                "                           ",
            palitra_color.white,
],
    //уровень 2
            [
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "  xxxxxxxxxxxxxxx          ",
                "  xR    b   r   x          ",
                "  x     b   r   x          ",
                "  xxrrrxxbbbxrrrx          ",
                " xx     x   x   x          ",
                " xB  @  b   x * x          ",
                " xx     x   x   x          ",
                "  xxrrrxxbbbx   x          ",
                "  x     g    g  x          ",
                "  x     g     g x          ",
                "  xG    g      gx          ",
                "  xxxxxxxxxxxxxxx          ",
                "                           ",
                "                           ",
                "                           ",
            palitra_color.blue,
],
    //уровень 3
            [
            "@x x x         x   x x     ",
            "      x x  x x    x    x x ",
            " xxxx     xxx x x   x x  x ",
            "      x  x    xxx xxx   xx ",
            " xx xxx x  xx    x x  x    ",
            " x      x x  x xxx    x x x",
            " xxxxx  x  x  r   xx xx  x ",
            "         x x x  x x     x  ",
            " x x   x   xxxxBxx  x x  x ",
            "  x x  xx x    b    x  x x ",
            " x   x     x x xx x  x x  x",
            "  x xx  x x    x  xx x xx  ",
            " x   x x  x x x x   x   x x",
            "   x     xx   x   x  x  x  ",
            " x  x x  x   xxxx xxxxx xxx",
            "  x x      x     x         ",
            "x   x xxx xxx xx  xxxx  gxg",
            "  x      x       xR    x   ",
            "bxxxxxxxgxxxxxxxxxxxxxx  * ",
            "                      Gx   ",
            palitra_color.white,
],
                //
                [	
	"rrrxgggxbbbxrrrxgggxbbbxggg",
	"@  b   r   g   b   g   r   ",
	" R b R r G g R b B g R r G ",
	"   b   r   g   b   g   r   ",
	"rrrxbbbxbbbxrrrxgggxbbbxrrr",
	"   g   r   g   b   g   r   ",
	" G g B r G g R b B g R r G ",
	"   g   r   g   b   g   r   ",
	"rrrxgggxbbbxrrrxgggxrrrxbbb",	
	"   b   r   g   b   b   r   ",
	" R b B r G g R b G b R r G ",
	"   b   r   g   b   b   r   ",
	"rrrxgggxbbbxrrrxgggxrrrxggg",
	"   b   r   r   b   r   g   ",
	" R b B r B r R b B r R g G ",
	"   b   r   r   b   r   g   ",
	"rrrxgggxbbbxgggxgggxgggxrrr",
	"   b   r   g   g   b   g   ",
	" R b B r G g B g G b R g * ",
	"   b   r   g   g   b   g   ",
	palitra_color.white,
],
    //уровень 4
            [
            "@                          ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBB ",
            "                         B ",
            " BBBBBBBBBBBBBBBBBBBBBBB B ",
            " B                     B B ",
            " B BBBBBBBBBBBBBBBBBBB B B ",
            " B B                 B B B ",
            " B B BBBBBBBBBBBBBBB B B B ",
            " B B BrrrrrB       B B B B ",
            " B B Br   rB       B B B B ",
            " B B Br * rB       B B B B ",
            " B B Br   rB       B B B B ",
            " B B BrrrrrBBBBBBBBB B B B ",
            " B B BR              B B B ",
            " B B BBBBBBBBBBBBBBBBB B B ",
            " B B                   B B ",
            " B BBBBBBBBBBBBBBBBBBBBB B ",
            " B                       B ",
            " BBBBBBBBBBBBBBBBBBBBBBBBB ",
            "                           ",
            palitra_color.white,
],
    //уровень 5
            [
            "R@                         ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBB ",
            "                         B ",
            " BBBBBBBBBBBBBBBBBBBBBBB B ",
            " B                     B B ",
            " B BBBBBBBBBBBBBBBBBBB B B ",
            " B B                 B B B ",
            " B B BBBBBBBBBBBBBBB B B B ",
            " B B Brrrrr        B B B B ",
            " B B Br   r        B B B B ",
            " B B Br * r        B B B B ",
            " B B Br   r        B B B B ",
            " B B BrrrrrBBBBBBBBB B B B ",
            " B B B               B B B ",
            " B B BBBBBBBBBBBBBBBBB B B ",
            " B B                   B B ",
            " B BBBBBBBBBBBBBBBBBBBBB B ",
            " B                       B ",
            " BBBBBBBBBBBBBBBBBBBBBBBBB ",
            "                           ",
            palitra_color.white,
],
    //уровень 6
            [
                "                           ",
                "                           ",
                "                           ",
                "          RRRRR            ",
                "       RRR     R           ",
                "      R   R RR  RRR        ",
                "      R R     R   R        ",
                "     R  gxxx  RRR R        ",
                "      RgG   b R   R        ",
                "       x     xR RRR        ",
                "       r  @  r   R         ",
                "     xxx     x R R         ",
                "    x   b    x R R         ",
                "   x     xxxxBg  R         ",
                "   x  *  x  Rb  R          ",
                "    x    x   RRR           ",
                "     x  x                  ",
                "      xx                   ",
                "                           ",
                "                           ",
            palitra_color.red,
],
    //конец
            [
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "   x   x   xxx   x   x     ",
                "   x   x  x   x  x   x     ",
                "   x   x  x   x  x   x     ",
                "   xxxxx  x * x  xxxxx     ",
                "       x  x   x      x     ",
                "       x  x   x      x     ",
                "       x   xxx       x     ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "             @             ",
                "                           ",
                "                           ",
            palitra_color.white,
]
];

window['maslevel'] = maslevel;